### PR TITLE
Fix publish and PR workflows

### PR DESCRIPTION
**Pull request by brunoanc**
Fixes the workflows for publishing and PR testing.

### CODE REVIEW

**Comment by brunoanc** [comment]
@Danielmelody There's still an issue with the publish workflow. Since it recompiles the kernel lib files (due to the `--features=ispc`, the related files are changed during the workflow. This will make `cargo publish` throw the following error:

```
 error: 4 files in the working directory contain changes that were not yet committed into git:

src/ispc/kernel_astc.rs
src/ispc/libkernel_astcx86_64-unknown-linux-gnu.a
src/ispc/libkernelx86_64-unknown-linux-gnu.a
src/ispc/kernel.rs

to proceed despite this and include the uncommitted changes, pass the `--allow-dirty` flag
```

We could:
a) Remove the `--features=ispc` from the workflow, so the libs don't get recompiled.
b) Restore the files before `cargo build` by using `git checkout`.
c) Commit the changed kernel files.
d) Ignore the warning with `--allow-dirty`, uploading the crate with the changed files.

What do you think?

**Comment by Danielmelody** [comment]
@PowerBall253 Great work here. We can proceed without `--features=ispc` now, as it will build only current platform, which is meaningless. We should support cross compilation for continuous deployment purpose later.

On the other hand, the build result of ispc kernel should not be any different if the compiler and the source ispc code is not changed, can you please look up into it to figure out why?

**Comment by brunoanc** [comment]
> We can proceed without --features=ispc now, as it will build only current platform, which is meaningless. We should support cross compilation for continuous deployment purpose later.

Alright, I'll remove it now then.

> On the other hand, the build result of ispc kernel should not be any different if the compiler and the source ispc code is not changed, can you please look up into it to figure out why?

For the .rs files, `bindgen`'s output will change depending on a lot of factors (OS, clang version, etc.). The `intel-tex-rs` repo the original code comes from solved this by removing the platform specific vars from the file, leaving only the generic bindings (which are enough for the task): <https://github.com/gwihlidal/intel-tex-rs/blob/master/src/ispc/kernel.rs>.

As for the actual libraries, besides specific OS version/distro and compiler version changes, there could also be differences in the timestamps generated by `ar`.

**Comment by Danielmelody** [comment]
OK, if you are ready please change the merge status to be ready for review, I will merge it.

**Pull request merged**
